opensafely-core/opensafely-cli

README.md

This is mainly because I forgot to enable the PyPI organisation secret
for this repo so it was unable to publish the last version.
BREAKING CHANGE: As we're releasing this publicly semver dictates it
should be version 1.0.

feat: Add note on testing

---

setup.py

It turns out clicking Update Selection is not sufficient to change which
repos have access to an org secret; you also need to click a separate
Save button.

fix: Actually maybe publish this time

---

.github/workflows/build_and_publish.yaml

This is convenient for contexts where we have access to Github but not
PyPI.

ci: Publish files as Github Release Assets

---

.github/workflows/tests.yml
opensafely/codelists.py
tests/fixtures/codelists/codelists.json
tests/fixtures/codelists/codelists.txt
tests/fixtures/codelists/opensafely-chronic-respiratory-disease.csv
tests/fixtures/codelists/opensafely-covid-identification.csv
tests/fixtures/codelists/opensafely-current-asthma.csv
tests/test_codelists.py
tests/test_packaging.py

This adds an `opensafely codelists check` command which verifies that the CSVs in your `codelists` folder match what's specified in `codelists.txt`. It does this by recording what files have been downloaded (and their hashes) in a `codelists.json` file.
There's some temporary code which spots that it's being run in a Github Action and falls back to using the old verification method (which checks against OpenCodelists) so that existing repos don't fail immediately under the new method.
Closes #12

Add `codelists check` command

---

opensafely/codelists.py
tests/test_codelists.py

Codelists owned by users are at codelists.opensafely.org/codelist/user/[username]/[codelist]/[version].

fix: Support user-namespaced codelists

---

opensafely/__init__.py
opensafely/pull.py
opensafely/upgrade.py
setup.py
tests/conftest.py
tests/test_pull.py
tests/test_upgrade.py

This is just a helpful wrapper around running pip upgrade step, but its
more user friendly
Additionally, we nag user to run the new upgrade command if we detect
a more recent of opensafely is available. Not quite auto-update, but
might get us quite far as is.
Note: we cache the latest version for 2 hours, to avoid spamming pypi on
every command.

feat: Add upgrade command and update available message

---

opensafely/pull.py
tests/conftest.py
tests/test_pull.py
tests/test_upgrade.py

- keeps the cli in sync with jobrunner
- added cohortextractor image as a consequence
- use text=True in subprocess.run() for better x-platform parsing
- refactored RunFixture to enforce check and text kwarg behaviour

fix: use jobrunner to supply list of images

---

opensafely/codelists.py
tests/test_codelists.py

We already implement this behaviour in our [test runner][1] but if this
really is the behaviour we want then its better to implement that here
and take the conditional out of the test runner.
[1]: https://github.com/opensafely-core/research-action/blob/30396ad13063b98d5573814448d6750e9bed823d/entrypoint.py#L46-L49

fix: Pass `codelists check` if no codelists dir exists

---

opensafely/pull.py
tests/fixtures/projects/bad.yaml
tests/fixtures/projects/noactions.yaml
tests/fixtures/projects/project.yaml
tests/test_pull.py

This will take a path to a project.yaml file, and use that to inform the
tool as to which images should be pulled locally.
The primary motivation for this is faster setup of development
environments, particularly with gitpod.io in mind.

feat: add --preseed option to pull command

---

.github/workflows/tests.yml
requirements.dev.txt

I was looking at https://github.com/opensafely/documentation/issues/485 and wondering what Python version someone might get if they install Python from Microsoft Store.
It's possible (though can't check) that soon-ish they'd get Python 3.10 when searching for Python.
So, it seems wise to run the tests with Python 3.10 here, because:
* the tests work (with a couple of dependency upgrades here)
* to flag any potential future issues that we might miss otherwise

test: Test with Python 3.10

---

setup.py

GitHub redirects the previous URL. But it's still nice to be directly
correct.

chore: Update URLs in setup.py

---

opensafely/codelists.py
opensafely/pull.py
tests/fixtures/codelists/codelists.txt
tests/test_pull.py

It's easy to include these and the error it produces is non-obvious.
Closes #57

fix: Strip trailing slash from codelist paths

---

.github/workflows/build_and_publish.yaml
.github/workflows/tests.yml
DEVELOPERS.md
README.md
setup.py

This sets the minimum version of Python we support to 3.8.

Switch to 3.8 as the base version

---

opensafely/jupyter.py

Its needed in windows to have a proper support for `docker run -t`,
which is needed to get pretty colors.

fix: jupyter: automatically use wintty if present

---

opensafely/check.py
tests/test_check.py

Github desktop is the recommended installation of git as per the opensafely docs.
It does not add `git` to the Windows path. Therefore when `opensafely check` tries to call git to ascertain the repository name, this can fail.
This PR parses the git config file instead.

fix: read git config instead of using git cli

---

opensafely/__init__.py
opensafely/pull.py
opensafely/upgrade.py
tests/test_pull.py

This is similar to how we prompt for the cli tool itself.
The docker registry API is horrible, and just looking up anything
requires an auth dance, even for public resources.

feat: prompt to update when docker images out of date

---

opensafely/check.py
repository_permissions.yaml
tests/fixtures/permissions/repository_permissions.yaml
tests/test_check.py

Amir has confirmed that there are no special restrictions on the therapeutics dataset so these warnings can be removed

Remove restrictions on therapeutics dataset

---

opensafely/__init__.py
opensafely/unzip.py
tests/test_unzip.py

This simply wraps gunzip as a helpful cross platform tool for users to
be able to examine gzip compressed outputs locally

feat: add unzip subcommand

---

opensafely/check.py
tests/fixtures/permissions/repository_permissions.yaml
tests/test_check.py

Restricts use of the ONS_CIS dataset.  Currently this means no studies can use it, until allowed studies are confirmed, and repos added to `repository_permissions.yaml`

Restrict ONS_CIS dataset

---

scripts/update-all-dependencies.sh

macOS ships with BSD sed so we need to support both BSD and GNU
versions.

Use cross-platform sed invocation

---

opensafely/__init__.py
opensafely/execute.py
tests/test_execute.py

This is for running ad-hoc OpenSAFELY actions. As an illustration, running this command:
opensafely exec foo:v1 do_something --a=1
Should do roughly the same thing as this action in `project.yaml`:
my_action:
run: foo:v1 do_something --a=1
The key difference is that rather than having `needs` and `outputs` control which files are available, we mount the entire workspace in so the command can read and write any files it likes.
This is motivated particularly by a desire to remove friction from the Data Builder tutorial. Being able to run commands, see log and error output immediately, and read and create arbitrary files provides a much smoother on-ramp than forcing everything through `project.yaml`.
It also means we can support commands like Data Builder's `create-dummy-tables` which are …

Add `opensafely exec` command

---

.github/workflows/build_and_publish.yaml
.github/workflows/tests.yml

Fixes #82.
Supersedes #102.
From Data Builder experience, updating the [github-tag-action may cause problems](https://github.com/opensafely-core/databuilder/issues/716), so I've left it.

ci: Update GitHub Actions

---

opensafely/pull.py
opensafely/upgrade.py
tests/test_pull.py
tests/test_upgrade.py

This didn't matter much before we added `opensafely exec`, but now we have that we want to be able to pipe commmand output around and so we need to keep the warnings out of stdout.

fix: Write warnings to stderr rather than stdout

---

repository_permissions.yaml

This adds [this repo](https://github.com/opensafely/ckd-coverage-ve/tree/main/analysis) to the list of repos allowed to use the UKRR variables.
This repo is linked to projects [88](https://www.opensafely.org/approved-projects/#project-88) and [110](https://www.opensafely.org/approved-projects/#project-110), approved to use the UKRR variables

add ckd coverage repo to ukrr allowed list

---

opensafely/__init__.py
opensafely/execute.py
opensafely/jupyter.py
opensafely/utils.py
tests/conftest.py
tests/test_execute.py
tests/test_jupyter.py
tests/test_utils.py

- fix: allow exit codes to pass through
- fix: handle possible winpty wrapper in RunFixture
- fix: Add new utils package with run_docker function
- chore: add a test for the jupyter command.
- fix: use run_docker with exec command

better docker execution

---

opensafely/__init__.py
opensafely/upgrade.py
tests/test_init.py
tests/test_upgrade.py

Added a global check to avoid spamming checking for updates on every
invocation, which was slow.
Remove the specific upgrade/version caching, as is wasn't needed give
the above.
Altogether, much simpler and future proof
Fixes #147 and fixes #37

fix: refactor periodic update checks

---

opensafely/jupyter.py
tests/test_jupyter.py

This allows jupyter notebooks to import from the top level directory of
the workspace code.
Fixes #160

fix: add PYTHONPATH=/workspace to jupyter invocation

---

opensafely/__init__.py

Can confuse them as to the actual error, expecially for pipeline
validation.
Passing --debug will show the traceback.

fix: hide traceback from users by default

---

opensafely/utils.py
tests/test_utils.py

Previously, it mistakenly affected all windows terminals, but its only the MINGW terminal provided by git-bash that is horrible.

fix: tweek winpty logic to only be for git-bash

---

repository_permissions.yaml

This repo is for @hendersonad and @ocarlile's work on OpenPROMPT. When merged, use of ehrQL's `open_prompt` table within this repo will no longer raise a warning, such as opensafely/openprompt-hrqol#10.

fix: Allow openprompt-hrqol to access open_prompt

---

repository_permissions.yaml

Allows access to the Clock Stops and Open Pathways tables for @alschaffer's opensafely/waiting-list repo.
Closes opensafely/waiting-list#4

feat: Allow access to waiting list tables

---

opensafely/codelists.py
tests/test_codelists.py

Fixes #225 
Part of the [plan for dealing with acute codelist rot](https://github.com/orgs/opensafely-core/projects/13/views/1?pane=issue&itemId=42536167)
OpenCodelists now has an endpoint that takes the content of a study repo's codelists.txt and codelists.json, and checks that the data that would be downloaded for the specified codelists is the same as the sha in the codelists.json file.  This is specifically intended to deal with changing VMPs in dm+d codelists, in case new mappings have been introduced since the codelist was downloaded into the study repo.
The new subcommand `check-upstream` just calls the opencodelists endpoint, and can be run on its own.  The existing `opensafely codelists check` command now also runs `check-upstream`, so `check` is a comprehensive check of both …

Add a new codelists check-upstream command

---

opensafely/pull.py
tests/conftest.py
tests/test_pull.py

- Add opensafely label in image filters.
- Support v2 python in opensafely pull

fix: support multiple versions in pull command

---

repository_permissions.yaml

I had missed that the `ckd-healthcare-use` repo was already on the list.

fix: duplicate repo name in permissions file

---

opensafely/check.py
tests/test_check.py

If the in-checkout version of `repository-permissions.yaml` is invalid, then the test will fail.
Closes #253

Test in-checkout copy of `repository-permissions.yaml`

---

DEVELOPERS.md
opensafely/__init__.py
opensafely/info.py
opensafely/pull.py
opensafely/upgrade.py
tests/conftest.py
tests/test_init.py
tests/test_pull.py
tests/test_upgrade.py

The primary purpose of this PR is to ignore dangling images, and thus un-break
`opensafely pull` for some users.
Also included is a related UX improvement to the `opensafely info` command, as
this would have helped diagnose the problems.
This also involved some clean up refactoring, moving the responsibility for
printing warnings to where it belongs.

fix: Ignore dangling images in opensafely pull

---

.github/workflows/build_and_publish.yaml
opensafely/info.py
opensafely/pull.py
tests/test_pull.py

- **fix: attempt to fix release action**
- **fix: manually filter for dangling images for older dockers**
- **Make info command throw exceptions rather than handle them**

fix: older docker doesn't support dangling=false filter

---

.github/workflows/tests.yml
opensafely/__init__.py
opensafely/upgrade.py
setup.py
tests/test_packaging.py

As a first step in exploring the `uv` story we make the minimal changes necessary to ensure that everything works correctly under `uv` with a recent version of Python. This involves:
* making explicit our implicit dependency on `setuptools`;
* prompting the user to upgrade by running `uv tool upgrade opensafely` rather than `opensafely upgrade` if they've used `uv` rather than `pip` to install it.
These changes ought to be invisible to existing users, but they mean it's now possible to get some users to try out `uv` on an experimental basis.
There's very little change in the production code here: as you might expect, most of the shenanigans are with the tests.
Relates to #277

Make it possible to install with `uv`

---

opensafely/__init__.py
opensafely/jupyter.py
opensafely/utils.py
pyproject.toml
tests/conftest.py
tests/test_jupyter.py
tests/test_rstudio.py
tests/test_utils.py

This fixes an ugly message for a user when something didn't work right.
There were two errors:
- a missing default definition of `response`
- the special formatting of exceptions was broken.
These were not covered by tests, as it was awkward to do. But its caused
breakage, so this PR grasps the nettle and adds coverage for:
- rstudio command opening the browser
- jupyter command getting metadata and opening the browser
- `open_browser` error cases
This required some refactoring of the SubprocessRunFixture, and some other
clean ups.
As a result, test coverage went up by 6%.
- **Refactor SubprocessRunFixture to handle concurrent declarations**
- **Explicitly mock open_browser call in test_rstudio.py**
- **Fully mock/test jupyter browser calls**
- **use requests rather than urllib, as its …

fix: test and fix error handling in open_browser

---

opensafely/jupyter.py
opensafely/rstudio.py
pyproject.toml
tests/test_jupyter.py
tests/test_rstudio.py

Adds a call to `docker_preflight_check()` at the beginning of the `opensafely jupyter` and `opensafely rstudio` subcommands. 
This ensures they give the same error message as `opensafely run` if they are started without Docker installed or running.
I had to move the coverage target back down 1 to 87.

Add Docker preflight check to opensafely jupyter and rstudio subcommands

---

opensafely/jupyter.py
opensafely/launch.py
opensafely/rstudio.py
opensafely/utils.py
tests/conftest.py
tests/test_launch.py

To use `opensafely launch rstudio` in codespaces, we need to run in the background.  This is more complex than just adding `&` to the invocation, as docker client is actually forwarding stdin/out/err from the docker server - its pretending to be a process we control, but its not really (another reason we should look at podman). We need to use `docker run -d`. So this change adds a --background flag.  This is actually really useful for testing, and allows us to add fully functional tests of `opensafely launch` that were very tricky to write when running in the foreground.
In addition, it would be helpful to make launch command idempotent, so if you re-run it, you reconnect to the old running instance, which will preserve state between codespace use and provide better UX.  We add a --force …

feat: add --background and --force options to launch command

---

opensafely/info.py
opensafely/pull.py
tests/test_info.py
tests/test_pull.py

Add `opensafely info --list-project-images [project.yaml]` command to print a list of all image versions.
This can be consumed by the codespaces tooling to know what runtime environments to set up.

List project image versions

---

repository_permissions.yaml

This was approved here:
https://bennettoxford.slack.com/archives/C02HJTL065A/p1740071960925689

Allow `post-covid-cvd` study to use `appointments`

---

opensafely/codelists.py
tests/test_codelists.py

Previously it was nearly impossible to add a draft codelist to codelists.txt as going to the URL in a browser would redirect to that codelist's builder URL, which would not pass the URL pattern validation.
Copying the draft codelist URL from a user's codelists page and then adding this to codelist.txt manually or via `codelists add` bypasses this block.
When a csv download of a draft codelist is requested from opencodelists it returns the HTML page for that codelist along with text stating its draft status, which the CLI would willingly put into a csv file in the codelists directory.
We don't want this behaviour and we don't want users to add draft codelists to projects as they are still mutable at this point.
This change checks for draft codelists and prevents their download.
Fixes #319

Handle draft codelists

---

opensafely/pull.py
tests/fixtures/projects/project.yaml
tests/test_info.py
tests/test_init.py
tests/test_pull.py

Some fixes to the pull command
- switch the default pulled versions to use v1 rather than latest, bump r's default to v2
- support pulling rstudio images, and default to v2

Support rstudio in opensafely pull, and update default versions

---

opensafely/launch.py
tests/test_launch.py

If we let docker pull them lazily it causes two problems
- it can take so long that the open browser thread times out
- if the user ran in the background, then there is no output, and it
looks like the command has hung
So, instead we ensure the relavnat image exists locally first, and if we
need to download it, we show that download output to the user

fix: ensure rstudio/python images exist before running launch command

---

opensafely/codelists.py
tests/test_codelists.py

Fixes #333 
We would like to enable Cloudflare's "bad bot" protections on OpenCodelists, `requests`'s standard UA of `python/requests` is flagged as a bot.
This PR introduces a bespoke user agent for OpenSAFELY CLI so that we can identify calls from the CLI

Custom UA for contacting opencodelists.org

---

DEVELOPERS.md

#339 failed to include a semantic commit message and so changes not deployed to pypi. This commit makes a minor formatting change to the developer docs and does include a semantic commit message such that a deploy will be triggered.

Reformat developer docs to trigger deploy

---

.github/workflows/tests.yml

The `windows-2019` GitHub Actions runner image is deprecated, and will be removed by 2025-06-30.
https://github.blog/changelog/2025-04-15-upcoming-breaking-changes-and-releases-for-github-actions/#windows-server-2019-is-closing-down

Replace `windows-2019` with `windows-2022`
