opensafely-core/opensafely-cli

MANIFEST.in

fix: Include SQL schema in package

---

opensafely/_vendor/jobrunner/job.py
opensafely/_vendor/jobrunner/project.py
vendor.txt

This just involves running:
```
./scripts/update-dependencies.sh
```

fix: Update to latest jobrunner

---

.github/workflows/build_and_publish.yaml
opensafely/_vendor/jobrunner/database.py
opensafely/_vendor/jobrunner/docker.py
opensafely/_vendor/jobrunner/local_run.py
opensafely/_vendor/jobrunner/log_utils.py
opensafely/_vendor/jobrunner/manage_jobs.py
opensafely/_vendor/jobrunner/retry_job.py
vendor.txt

And fixes the broken YAML in the workflow file :(

fix: Update to latest job-runner

---

opensafely/_vendor/jobrunner/config.py
opensafely/_vendor/jobrunner/create_or_update_jobs.py
opensafely/_vendor/jobrunner/local_run.py
vendor.txt

This switches to using opensafely-core Docker images

feat: update to opensafely 2.10

---

opensafely/__init__.py
opensafely/pull.py
tests/test_pull.py

By default it will only update images that are already present locally,
but you can force all images with --force. You can also pull a specific
image.

Add a 'pull' subcommand, which updates docker images.

---

opensafely/upgrade.py
tests/test_upgrade.py

fix: more robust invocation of pip in upgrade command

---

opensafely/__init__.py
opensafely/upgrade.py
tests/test_packaging.py

Also fixes a couple of edge case bugs and smoketests the upgrade command.
Closes #36

Fix `upgrade` command on Windows

---

.github/workflows/build_and_publish.yaml

Before we switch the default branch name.

ci: update branch name in workflow

---

DEVELOPERS.md
opensafely/_vendor/jobrunner/config.py
opensafely/_vendor/jobrunner/create_or_update_jobs.py
opensafely/_vendor/jobrunner/docker.py
opensafely/_vendor/jobrunner/docker_stats.py
opensafely/_vendor/jobrunner/local_run.py
opensafely/_vendor/jobrunner/manage_jobs.py
opensafely/_vendor/jobrunner/project.py
opensafely/_vendor/jobrunner/run.py
scripts/update-all-dependencies.sh
scripts/update-jobrunner.sh
vendor.txt

And add a script to allow updating just jobrunner and avoid pulling in other potentially problematic changes.

Update to jobrunner v2.24.1

---

opensafely/__init__.py
opensafely/check.py
tests/test_check.py

Implementation of ideas originally expressed in [bash script](https://github.com/Jongmassey/research_repository_permissions) to allow for checking study definitions for usage of restricted datasets

Check-datasource

---

.gitignore
opensafely/__init__.py
opensafely/check.py
opensafely/codelists.py
opensafely/jupyter.py
opensafely/pull.py
opensafely/upgrade.py
tests/test_check.py
tests/test_codelists.py
tests/test_packaging.py
tests/test_pull.py
tests/test_upgrade.py

This will run jupyter lab in the current directory using the opensafely
python image. It should behave the same as running `jupyter lab`
manually.

feat: add an initial jupyter command

---

opensafely/jupyter.py

It's hard to test this on different users setups, so make more debugging
output available.

fix: add more debug output to jupyter command

---

opensafely/jupyter.py

The goal is to automatically wrap our call to "docker run -it ..." in
winpty if we detect we are running in git-bash's broken default
terminal.
Both cmd.exe and Windows Terminal provide a proper tty so do not need
this.
The problem is that passing the `-v=...` paths as arguments to winpty
forces them through git-bash path translation, which we had previously
been able to avoid as we were going via subprocess.run(), and the path
translation mucked up the -v mappings.
So, this change does two thinks:
1) try to detect when were are in the severely limit git-bash/mingw
environement, and wrap the docker command in winpty only then.
2) Escape the docker side of the mount from git-bash with
`://workspace`, and revert to using standard backslash paths on the
host side.
This has been manually …

fix: jupyter another attempt at dealing with tty in git-bash

---

opensafely/_vendor/certifi/LICENSE
opensafely/_vendor/charset-normalizer.LICENSE
opensafely/_vendor/idna/LICENSE.md
opensafely/_vendor/jobrunner/cli/local_run.py
opensafely/_vendor/jobrunner/config.py
opensafely/_vendor/jobrunner/executors/__init__.py
opensafely/_vendor/jobrunner/executors/local.py
opensafely/_vendor/jobrunner/executors/logging.py
opensafely/_vendor/jobrunner/job_executor.py
opensafely/_vendor/jobrunner/lib/docker.py
opensafely/_vendor/jobrunner/lib/log_utils.py
opensafely/_vendor/jobrunner/lib/lru_dict.py
opensafely/_vendor/jobrunner/project.py
opensafely/_vendor/jobrunner/reusable_actions.py
opensafely/_vendor/jobrunner/run.py
tests/test_pull.py
vendor.txt

To support the `databuilder` image.

feat: Upgrade job-runner to v2.38.0

---

opensafely/check.py
repository_permissions.yaml
tests/fixtures/permissions/repository_permissions.yaml
tests/test_check.py

feat: Restrict ISARIC dataset

---

tests/test_check.py

Refactor the tests for check.py so that tests for new restricted datasets can be added by just adding to the fixture in `tests/fixures/permissions/repository-permissions.yaml`
The existing tests were very comprehensive, but very difficult to read, and adding tests for a new restricted dataset involved adding some quite opaque text to the tests (I've had to do this 2 or 3 times now and it's been a puzzle every time).   These changes mean that the test repos that are used in the parametrized `test_check` are retrieved from the `repository-permissions.yaml` fixture, and the mock study definition generated by the tests is built using the restricted functions in `checks.py`, with deterministic variable names.
To add a new restricted dataset to the tests, you'll just add additional data to the …

Refactor checks tests to simplify tests for new restricted datasets

---

repository_permissions.yaml

resolves #116 
Project https://jobs.opensafely.org/staff/applications/d9b2/

feat: renal short data report permission

---

opensafely/__init__.py
opensafely/info.py

The goal is to help users be more aware of their docker resources.

Add basic info command

---

opensafely/_vendor/jobrunner/cli/local_run.py
opensafely/_vendor/jobrunner/cli/migrate.py
opensafely/_vendor/jobrunner/config.py
opensafely/_vendor/jobrunner/lib/commands.py
opensafely/_vendor/jobrunner/lib/database.py
opensafely/_vendor/jobrunner/service.py
opensafely/_vendor/pipeline/models.py
opensafely/_vendor/pipeline/validation.py
tests/test_pull.py
vendor.in
vendor.txt

feat: Upgrade to job-runner 2.57.1

---

opensafely/_vendor/certifi/LICENSE
opensafely/_vendor/charset-normalizer.LICENSE
opensafely/_vendor/idna/LICENSE.md
opensafely/_vendor/jobrunner/lib/database.py
opensafely/_vendor/ruamel/LICENSE
pyproject.toml

This executes correctly against a study.

fix: Substitute path to jobrunner.models

---

repository_permissions.yaml

https://bennettoxford.slack.com/archives/C010SJ89SA3/p1665746539560419?thread_ts=1665743335.586349&cid=C010SJ89SA3
permitted by @amirmehrkar , requested by @alexwalkerepi

allow opensafely/bias to use ons_cis

---

.gitignore
pyproject.toml

Refs: opensafely-core/repo-template#85

Update black config

---

opensafely/__init__.py
opensafely/execute.py

- fix: quiten the noisy logging in tracing
- fix: drive by fix of verbose parameter in exec
Fixes #177

fix trace warnings

---

repository_permissions.yaml

this repo: https://github.com/opensafely/isaric-exploration
this project: https://jobs.opensafely.org/datalab/validation-of-isaric-sus-phosp-data-for-covid-related-hospital-admissions/

add permissions for isaric exploration repo

---

opensafely/check.py

See opensafely-core/ehrql#1396

Restrict `ons_cis_raw`

---

opensafely/check.py
tests/fixtures/permissions/repository_permissions.yaml

See opensafely-core/ehrql#1646 and opensafely-core/ehrql#1651.

Restrict access to Clock Stops and Open Pathways

---

requirements.dev.txt

Dependabot currently wants to run with a newer Python version which removes required dependencies.

chore: Update dev requirements

---

opensafely/check.py
repository_permissions.yaml
tests/fixtures/permissions/repository_permissions.yaml

See https://github.com/opensafely-core/ehrql/issues/1970

Restrict appointments table

---

repository_permissions.yaml

Some more repos that I have determined to be okay to use appointments data.

feat: add more appointments permissions

---

repository_permissions.yaml

I've previously spoken to the researcher about their use of the data and think it's fine - specifically, they're using the data as a variable in a model (as a proxy for healthcare usage), and not as an outcome variable.

add another appointments data exception

---

repository_permissions.yaml

Grant the winter-pressures-phase-II repository access to the appointments table. Liam has confirmed[^1] that the application for the associated project (172) requests access to this table.
[^1]: https://bennettoxford.slack.com/archives/C04NHSU5DRB/p1727338710394969

winter-pressures-phase-II -> appointments

---

opensafely/check.py

feat: Restrict UKRR dataset

---

repository_permissions.yaml

Grant access to UKRR dataset

---

opensafely/launch.py

Spotted as soon as it was published :facepalm:

fix: fix incorrect launch --help language

---

repository_permissions.yaml

This was approved here:
https://bennettoxford.slack.com/archives/C02HJTL065A/p1740071960925689

Allow further `post-covid-*` studies to use `appointments`

---

repository_permissions.yaml

Grant metformin_covid appointments access

---

DEVELOPERS.md

I've opted to keep the detail in a separate issue where it can more easily be edited, rather than freezing it into the repo.

Update DEVELOPERS.md to reflect job-runner changes
